// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_YHsh_Fbd0sR_qoTGrN_BFAsccs_zszQ',
    appId: '1:1095654129175:web:32fcad871271c82d6fe652',
    messagingSenderId: '1095654129175',
    projectId: 'crisisnexus-bf9fc',
    authDomain: 'crisisnexus-bf9fc.firebaseapp.com',
    storageBucket: 'crisisnexus-bf9fc.firebasestorage.app',
    measurementId: 'G-DHX6DK9EGH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhUeywV-xVCCmkuAZLmw5vmoPoOZgcK_c',
    appId: '1:1095654129175:android:34abc7704648879d6fe652',
    messagingSenderId: '1095654129175',
    projectId: 'crisisnexus-bf9fc',
    storageBucket: 'crisisnexus-bf9fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjYSSaF6P2vXiPw7Fej2RpVXZvxgqxdK0',
    appId: '1:1095654129175:ios:24acf7c3464d9f556fe652',
    messagingSenderId: '1095654129175',
    projectId: 'crisisnexus-bf9fc',
    storageBucket: 'crisisnexus-bf9fc.firebasestorage.app',
    iosBundleId: 'com.example.crisisNexus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjYSSaF6P2vXiPw7Fej2RpVXZvxgqxdK0',
    appId: '1:1095654129175:ios:24acf7c3464d9f556fe652',
    messagingSenderId: '1095654129175',
    projectId: 'crisisnexus-bf9fc',
    storageBucket: 'crisisnexus-bf9fc.firebasestorage.app',
    iosBundleId: 'com.example.crisisNexus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_YHsh_Fbd0sR_qoTGrN_BFAsccs_zszQ',
    appId: '1:1095654129175:web:63a16f280941278e6fe652',
    messagingSenderId: '1095654129175',
    projectId: 'crisisnexus-bf9fc',
    authDomain: 'crisisnexus-bf9fc.firebaseapp.com',
    storageBucket: 'crisisnexus-bf9fc.firebasestorage.app',
    measurementId: 'G-05VRQ23N21',
  );
}
